// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: arquillian-managed
:page-duration: 15 minutes
:page-releasedate: 2019-02-01
:page-guide-category: none
:page-description: Learn how to test your microservices with the Arquillian managed container and JUnit.
:guide-author: Open Liberty
:page-tags: ['Maven']
:page-related-guides: ['cdi-intro','rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Testing microservices with Arquillian managed container
:page-seo-description: Learn how to test your microservices with Arquillian managed container
= Testing microservices with Arquillian managed container

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to develop tests for your microservices with the Arquillian managed container and run the tests on Open Liberty.

== What you'll learn
You will learn how to develop tests for your microservices using the
https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed[Arquillian Liberty Managed container^]
and JUnit with Maven on Open Liberty. http://arquillian.org/[Arquillian^] is a testing platform to develop
automated functional, integration and acceptance tests for your Java applications.
Arquillian sets up the test environment and is able to handle the application server lifecycle for you,
so you can focus on writing tests. In this guide, you will develop the Arquillian tests that use JUnit
as the runner and build your tests with Maven. The Liberty Maven plug-in simplifies the process of managing
Arquillian dependencies and setting up your Arquillian managed container.

The application that you will work with is an `inventory` service that stores information about various systems.
The `inventory` service communicates with the `system` service on a particular host to retrieve its
system properties and stores them. You will develop functional and integration tests for the microservices.
You will learn about the configurations you need to run your tests on Open Liberty with the Arquillian
Liberty Managed container using the Maven build tool.

[role="command"]
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

To try running the finished application with the Arquillian tests, navigate to the `finish` directory
and run the Maven build.

[role="command"]
```
mvn install
```

You should see the console output indicating that your build is successful and the tests have passed.

== Developing Arquillian tests

You'll develop tests that use Arquillian and JUnit to verify the `inventory` microservice as an endpoint
and the functions of the inventory resource class.
The code for the microservices is provided to you under the `src/main/java/io/openliberty/guides` directory.

Navigate to the `start` directory to begin.

[role="code_command", subs="quotes"]
----
#Create the `InventoryArquillianTests` test class.#
`src/test/java/it/io/openliberty/guides/inventory/InventoryArquillianTests.java`
----

InventoryArquillianTests.java
[source, Java, linenums, indent=0, role="code_column"]
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryArquillianTests.java[tags=**;!copyright;]
----

Notice the JUnit Arquillian runner is being used to run the tests, instead of the standard JUnit runner.
The [hotspot=29]`@RunWith` annotation at the top of the class tells JUnit to run the tests using Arquillian.

The method annotated by [hotspot=36-41]`@Deployment` defines the content of the
web archive, which is going to be deployed to Open Liberty application server.
The tests are run either on or against the server.
The [hotspot=36]`testable = true` attribute enables the deployment to
run in-container tests, which means the tests are run on the server.

Notice the [hotspot=32 hotspot=38]`arquillian-managed.war` name used for the web
archive. It is necessary if you don't want a randomly generated web archive name.

ShrinkWrap is used to create the web archive.
All of the packages in this service must be added to the web archive; otherwise,
the code compiles successfully but fails at runtime when the injection of the
testing resource class takes place.
You can learn about the ShrinkWrap archive configuration in the
http://arquillian.org/guides/shrinkwrap_introduction/[Arquillian guide^].

The [hotspot=43]`@ArquillianResource` annotation is used to retrieve the
`\http://localhost:9080/arquillian-managed/` base URL for this web service.
The annotation provides the host name, port number and web archive
information for this service, so you don't need to hardcode these values
in the test case. Notice the `arquillian-managed` WAR name that was specified
in the web archive, it's needed  when the `inventory` service communicates
with the `system` service to get the system properties.

The [hotspot=52-82]`testInventoryEndpoints` method is an integration
test to test the `inventory` service endpoints. The [hotspot=50]`@RunAsClient`
annotation added in this test case indicates that this test case is to be run
on the client side, which means the tests are run against the managed container.
The endpoint test case first calls the
`\http://localhost:9080/{WARNAME}/inventory/systems/{hostname}` endpoint with
the `localhost` host name to add its system properties to the inventory.
The test verifies that the system property for the local and service JVM match.
Then, the test method calls the
`\http://localhost:9080/{WARNAME}/inventory/systems` endpoint.
The test checks that the inventory should have one host and
that should be `localhost`. The test also verifies that the system property
stored in the inventory for the local and service JVM match.

Contexts and Dependency Injection (CDI) is used to inject an instance of the
[hotspot=46-47]`InventoryResource` class into this test class.
You can learn more about CDI in the
https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices^] guide.
The instance is then tested by the [hotspot=86-97]`testInventoryResourceFunctions` method.
This test case calls the [hotspot=89]`listContents()` method to get all systems
 are stored in this inventory
and verifies that one system is found and it's `localhost`.
Notice the functional test case doesn't store any system in the inventory,
the `localhost` system is from the endpoint test case that ran before this test case.
The [hotspot=51 hotspot=85]`@InSequence` Arquillian annotation guarantees the test sequence.
The sequence is important for the two tests, as the results in the first test impacts the second one.

The test cases are ready to run.
You will configure the Maven build and the Liberty application server to run them.

== Configuring Arquillian with Liberty

Configure your build to use the Arquillian Liberty Managed container
and set up your Open Liberty server to run your test cases by configuring the `server.xml`.

=== Configuring your test build

First, configure your test build with Maven. All of the Maven configuration takes
place in the [hotspot]`pom.xml` file, which is provided for you.

pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/pom.xml[tags=**;]
----

Let's look into each of the required elements for this configuration.
You need the [hotspot=7-11]`liberty-maven-app-parent` block,
which configures the Liberty Maven plug-in with the default executions necessary
for setting up your managed Liberty server.

You also need the [hotspot=39-45]`arquillian-bom` Bill of Material.
It's a Maven artifact that defines the versions of Arquillian dependencies to
make dependency management easier.

The [hotspot=115-121]`arquillian-liberty-managed-junit` dependency bundle,
which includes all the core dependencies is required to run the Arquillian tests on a
managed Liberty container using JUnit. You can learn more about the
https://github.com/OpenLiberty/arquillian-liberty-dependencies[Arquillian Liberty dependency bundles^].
The [hotspot=122-126]`shrinkwrap-api` dependency allows you to create your test
archive which is packaged into a WAR file and deployed to the Open Liberty server.

The [hotspot=140-173]`maven-failsafe-plugin` runs your Arquillian integration tests using JUnit.

Lastly, you need the [hotspot=174-219]`liberty-maven-plugin`
configuration that specifies your Open Liberty runtime and uses
the [hotspot=215]`configure-arquillian` goal to automatically create and
configure your `arquillian.xml` file.
This goal retrieves the core `wlpHome`, `serverName`, and `httpPort` parameter
values automatically from the Liberty Maven plug-in configuration,
and also allows you to specify additional `arquillian.xml` parameters directly
in your POM.
You can see the parameter values in your `arquillian.xml` file after you run your tests.
The parameter values are needed for Arquillian to start the Liberty application
server in order to run the managed container tests.
You can learn more about the [hotspot=215]`configure-arquillian` goal in the
https://github.com/WASdev/ci.maven/blob/master/docs/configure-arquillian.md[documentation^].
Also, notice in the configuration that [hotspot=194]`skipTestServer` is set to
true to skip the `test-start-server`
and `test-stop-server` goals defined in the [hotspot=7-11]`liberty-maven-app-parent`.
The test server configuration is skipped because Arquillian is managing the
server lifecycle when it runs the tests.

=== Configuring the server.xml

Now that you're done configuring the build tool, you will set up your
Open Liberty server to run your test cases by configuring
the [hotspot]`server.xml` file.

Take a look at the [hotspot]`server.xml` file.

server.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[tags=**;]
----

The [hotspot=9]`localConnector` feature is required by the Arquillian Liberty
Managed container to connect to and communicate with the Open Liberty runtime.
The [hotspot=10]`servlet` feature is required during the deployment of the
Arquillian tests in which servlets are created to perform the in-container testing.


== Running the tests

It's now time to build and run your Arquillian test.
Run the Maven build command in the `start` directory.

[role="command"]
```
mvn install
```

In the test output, you see the application server was launched, and that the web archive,
`arquillian-managed` is started as an application in the server.
Then, the tests are being run and the results are reported.

Following the execution of the tests, the test application is automatically
undeployed and the server is shut down.
You should then get a message indicating that the build and tests are successful.

[source, role="no_copy"]
----
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.inventory.InventoryArquillianTests
...
[AUDIT   ] CWWKE0001I: The server ArquillianManagedServer has been launched.
[INFO    ] CWWKE0002I: The kernel started after 2.069 seconds
[INFO    ] CWWKF0007I: Feature update started.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[INFO    ] CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host localhost  (IPv4: 127.0.0.1) port 9080.
[INFO    ] CWWKZ0018I: Starting application microservices-arquillian-managed-test.
...
[INFO    ] SRVE0169I: Loading Web Module: microservices-arquillian-managed-test.
[INFO    ] SRVE0250I: Web Module microservices-arquillian-managed-test has been bound to default_host.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application microservices-arquillian-managed-test started in 4.276 seconds.
[INFO    ] SESN0176I: A new session context will be created for application key default_host/
[INFO    ] CWWKZ0018I: Starting application arquillian-managed.
...
[AUDIT   ] CWWKF0011I: The server ArquillianManagedServer is ready to run a smarter planet.
...
[INFO    ] SRVE0169I: Loading Web Module: arquillian-managed.
[INFO    ] SRVE0250I: Web Module arquillian-managed has been bound to default_host.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/arquillian-managed/
...
[AUDIT   ] CWWKZ0001I: Application arquillian-managed started in 0.957 seconds.
...
[INFO    ] Setting the server's publish address to be /inventory/
[INFO    ] SRVE0242I: [arquillian-managed] [/arquillian-managed] [io.openliberty.guides.inventory.InventoryApplication]: Initialization successful.
[INFO    ] Setting the server's publish address to be /system/
[INFO    ] SRVE0242I: [microservices-arquillian-managed-test] [/] [io.openliberty.guides.system.SystemApplication]: Initialization successful.
[INFO    ] SRVE0242I: [arquillian-managed] [/arquillian-managed] [ArquillianServletRunner]: Initialization successful.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/arquillian-managed/
[INFO    ] SRVE0253I: [arquillian-managed] [/arquillian-managed] [ArquillianServletRunner]: Destroy successful.
[INFO    ] SRVE0253I: [arquillian-managed] [/arquillian-managed] [io.openliberty.guides.inventory.InventoryApplication]: Destroy successful.
[AUDIT   ] CWWKZ0009I: The application arquillian-managed has stopped successfully.
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.355 s - in it.io.openliberty.guides.inventory.InventoryArquillianTests
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.875 s
[INFO] Finished at: 2019-02-12T14:40:43-05:00
[INFO] ------------------------------------------------------------------------
----

== Great work! You're done!

You have just completed building some functional and integration tests with the
Arquillian Liberty Managed container to run the tests for your microservices
on Open Liberty.

You can continue to try one of the related guides to learn more about the
technologies that you come across in this guide.

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]
