// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide
:projectid: arquillian-managed
:page-duration: 15 minutes
:page-releasedate: 2018-11-30
:page-guide-category: none
:page-description: Learn how to test your application using the Arquillian Liberty Managed container and JUnit.
:page-tags: ['Maven', 'Gradle']
:page-related-guides: ['cdi-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Arquillian Managed container testing
:page-seo-description: Testing your application with Arquillian Liberty Managed container
= Testing with the Arquillian Managed container

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to run integration tests for your application using the Arquillian Liberty Managed container in Open Liberty.

== What you'll learn
You will learn how to run integration tests for your application using the https://github.com/OpenLiberty/liberty-arquillian/blob/master/liberty-managed/README.md[Arquillian Liberty Managed container] and JUnit with Maven or Gradle in Open Liberty. For either of the build tools, you will also learn how to take advantage of features in the Liberty plugin that simplifies the process of managing Arquillian dependencies and setting up your managed container.

http://arquillian.org/[Arquillian] is a testing platform to develop automated integration, functional and acceptance tests for your java applications. Arquillian Liberty Managed container is an adaptor that implements the Arquillian's `DeployableContainer`. It's capable of managing the local Liberty server operations, packaging the tests as a `WAR` to be deployed to the Liberty server and then running the tests on the server.

You will learn to configure a example application to use the Liberty Arquillian Managed container adaptor with the Maven or Gradle build tool and develop an integration test for the application to run in Open Liberty.

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

To try running the finished application with the Arquillian test, navigate to the `finish` folder and execute the Maven or Gradle build.

If you're using Maven, run these commands:

```
cd finish
mvn install
```

If you're using Gradle, run these commands:

```
cd finish
gradle build
```

Between the server start and stop messages, you should see the following console output indicating that your test has passed.

[source, text, indent=0, role="no_copy"]
----
PhraseBuilder <init>
PhraseBuilder <init>
PhraseBuilder initialize
Hello, Earthling!
----

A message indicating a successful build follows shortly after the test outputs.

== Configuring your test build

For instructions on configuring your test build with Gradle, go to the "Using Gradle" section below.

Navigate to the `start` directory to begin.

=== Using Maven

All of the Maven configuration will take place in the `pom.xml` file.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=**]
----

Let's look into each of the required elements for this configuration. First, the Liberty Maven App Parent POM configures the Liberty Maven Plugin with the default executions necessary for setting up your managed Liberty server.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddLibertyMavenAppParent]
----

Next, the Arquillian Bill of Materials (BOM) is a Maven artifact which defines versions of dependencies to make dependency management easier.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddArquillianBOM]
----

Next, refer to the Arquillian Liberty Managed JUnit dependency bundle and the Arquillian Shrinkwrap API. The dependency bundle includes all the core dependencies for running Arquillian tests on a managed Liberty container using JUnit. You can learn more about the https://github.com/OpenLiberty/arquillian-liberty-dependencies[Arquillian Liberty dependency bundles]. The Shrinkwrap API allows you to create your test archive which is packaged into a WAR and deployed to the Open Liberty server.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddArquillianLibertyManagedJUnitAndShrinkwrapAPIDependency]
----

Finally, refer to the Maven Failsafe Plugin and the Liberty Maven Plugin. The failsafe plugin is used to run your JUnit integration tests, while the Liberty Maven Plugin configuration specifies your Open Liberty runtime and uses the `configure-arquillian` goal to automatically create and configure your `arquillian.xml`. This goal retrieves the core `wlpHome`, `serverName`, and `httpPort` parameter values automatically from the Liberty Maven Plugin configuration, and also allows you to specify additional `arquillian.xml` parameters directly in your POM in an `arquillianProperties` dictionary. You can learn more about the the `configure-arquillian` goal in the https://github.com/WASdev/ci.maven/blob/master/docs/configure-arquillian.md[complete documentation]. Also notice in the configuration that `skipTestServer` is set to true to skip the `test-start-server` and `test-stop-server` goals defined in the Liberty Maven Application Parent. This is because Arquillian is managing the server lifecycle when it runs the tests.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddMavenFailsafeAndLibertyMavenPlugins]
----

=== Using Gradle

For instructions on configuring the test build with Maven, scroll up to the "Using Maven" section above.

All of the Gradle configuration will take place in the `build.gradle` file.

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=**]
----

Let's look into each of the required elements for this configuration. First, refer to the Liberty Gradle Plugin and Gradle dependency management plugin as part of the buildscript dependencies. The Liberty Gradle Plugin allows you to manage your Liberty server, while the dependency management plugin brings support for Maven BOMs (Bill of Materials) to Gradle. You can learn more about the https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle[dependency management plugin].

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=AddLibertyAndDependencyManagementPlugins]
----

Next, the apply action is a required for the Liberty Gradle Plugin and the Gradle dependency management plugin.

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=ApplyLibertyAndDependencyManagementPlugins]
----

Next, the Liberty server configuration is needed to point the plugin to the location of your `server.xml`. You can also optionally assign a server name as shown below.

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=AddLibertyServerConfiguration]
----

Next, the Arquillian Bill of Materials (BOM) is a Maven artifact which defines versions of dependencies to make dependency management easier.

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=AddArquillianBOMDependency]
----

Then, refer to the test dependencies and the Open Liberty runtime to the `dependencies` section. The Arquillian Liberty Managed JUnit dependency bundle includes all the core dependencies for running Arquillian tests on a managed Liberty container using JUnit. You can learn more about the https://github.com/OpenLiberty/arquillian-liberty-dependencies[Arquillian Liberty dependency bundles]. The Shrinkwrap API allows you to create your test archive which is packaged into a WAR and deployed to the Open Liberty server. You also need to point to the `tools.jar` file provided by the JDK.

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=AddTestDependencyAndOpenLibertyRuntime]
----

Finally, refer to the test configuration. Notice that the tests depend on the `configureArquillian` task. This task automatically creates and configures your `arquillian.xml` by retrieving the core `wlpHome`, `serverName`, and `httpPort` parameter values from the Liberty Gradle Plugin configuration. It also allows you to specify additional `arquillian.xml` parameters directly in your `build.gradle` file in an `arquillianConfiguration` dictionary. You can learn more about the `configureArquillian` goal in the https://github.com/WASdev/ci.gradle/blob/master/docs/configureArquillian.md[complete documentation].

[source, text, indent=0, role="no_copy"]
----
include::finish/build.gradle[tags=AddTestConfiguration]
----

== Configuring the server.xml

Now that you're done configuring the build tool of your choice, open the `src/test/resources/server.xml` file:

[source, xml, indent=0, role="no_copy"]
----
include::finish/src/test/resources/server.xml[tags=**]
----

The `localConnector` feature in the `featureManager` block is required by the Arquillian Liberty Managed container in order to connect to and communicate with the Open Liberty runtime. The `servlet` feature is required during the deployment of the Aquillian tests in which servlets are created to perform the in-container testing.

== Adding your Arquillian test

You're now ready to write your test. Notice that the source of the starting project includes two classes, `Greeter` and `PhraseBuilder`. The `Greeter` class injects an instance of the `PhraseBuilder` class, and invokes a method on it to create a greeting. Your test class will use Arquillian and JUnit to test this functionality.

Create the `GreeterIT` test class in the `src/test/java/it/io/openliberty/guides/arquillian/example/GreeterIT.java` file:

[source, Java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/arquillian/example/GreeterIT.java[tags=**;!copyright;!comment]
----

The first thing you should notice is that the JUnit Arquillian runner is being used to run the tests, instead of the standard JUnit runner. This is specified using the `RunWith` annotation at the top of the class, and tells JUnit to run the tests using Arquillian.

The next important item is the `@Deployment` block. The ShrinkWrap test archive's contents are defined here, which is going to be deployed to Open Liberty to run the in-container tests. Notice the inclusion of the `Greeter` and `PhraseBuilder` classes. Without these, the code compiles successfully but fails at runtime when the injection of the `Greeter` class takes place.

CDI is used to inject an instance of the Greeter class. It is then tested by the `should_create_greeting` method, which validates that it creates the correct greeting based on the input.

== Running the tests

It's now time to build and run your Arquillian test. Run the command below that corresponds to your build tool of choice.

For Maven:

```
mvn clean install
```

For Gradle:

```
gradle clean build
```

In either case, notice that the server is created and started, with a test application built from your ShrinkWrap archive that is deployed at `http://localhost:9080/test/` during the build process. You should see the initialization and execution of the test:

```
PhraseBuilder <init>
PhraseBuilder <init>
PhraseBuilder initialize
Hello, Earthling!
```

Following the execution of the test, the test application is automatically undeployed and the server is shut down. You should then get a message indicating that the build was successful.

== Great work! You're done!

include::{common-includes}/finish.adoc[]
