// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: arquillian-managed
:page-duration: 15 minutes
:page-releasedate: 2019-03-08
:page-guide-category: none
:page-description: Learn how to test your microservices with the Arquillian managed container and JUnit on Open Liberty.
:guide-author: Open Liberty
:page-tags: ['Maven']
:page-related-guides: ['cdi-intro','rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Testing microservices with Arquillian managed container
:page-seo-description: A tutorial on how to test your microservices with the Arquillian managed container for Open Liberty
= Testing microservices with the Arquillian managed container

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to develop tests for your microservices with the Arquillian managed container and run the tests on Open Liberty.

== What you'll learn

You will learn how to develop tests for your microservices by using the
https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed[Arquillian Liberty Managed container^]
and JUnit with Maven on Open Liberty. http://arquillian.org/[Arquillian^] is a testing framework to develop
automated functional, integration and acceptance tests for your Java applications.
Arquillian sets up the test environment and handles the application server lifecycle for you
so you can focus on writing tests.

You will develop Arquillian tests that use JUnit
as the runner and build your tests with Maven using the Liberty Maven plug-in.
This technique simplifies the process of managing
Arquillian dependencies and the setup of your Arquillian managed container.

You will work with an `inventory` microservice, which stores information about various systems.
The `inventory` service communicates with the `system` service on a particular host to retrieve its
system properties and store them. You will develop functional and integration tests for the microservices.
You will also learn about the Maven and server configurations so that you can run
your tests on Open Liberty with the Arquillian Liberty Managed container.

[role="command"]
include::{common-includes}/gitclone.adoc[]


== Developing Arquillian tests

Navigate to the `start` directory to begin.

You'll develop tests that use Arquillian and JUnit to verify the `inventory` microservice as an endpoint
and the functions of the `InventoryResource` class.
The code for the microservices is in the `src/main/java/io/openliberty/guides` directory.

[role="code_command", subs="quotes"]
----
#Create the `InventoryArquillianTests` test class.#
`src/test/java/it/io/openliberty/guides/inventory/InventoryArquillianTests.java`
----

InventoryArquillianTests.java
[source, Java, linenums, indent=0, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryArquillianTests.java[]
----

Notice that the JUnit Arquillian runner runs the tests instead of the standard JUnit runner.
The [hotspot=RunWith]`@RunWith` annotation preceding the class tells JUnit to run the tests by using Arquillian.

The method annotated by [hotspot=Deployment]`@Deployment` defines the content of the
web archive, which is going to be deployed onto the Open Liberty server.
The tests are either run on or against the server.
The [hotspot=Testable]`testable = true` attribute enables the deployment to
run the tests "in container", that is the tests are run on the server.

Notice the [hotspot=warName hotspot=WebArchive]`arquillian-managed.war` name that is used for the web
archive. This name is necessary if you don't want a randomly generated web archive name.

The ShrinkWrap API is used to create the web archive.
All of the packages in the `inventory` service must be added to the web archive; otherwise,
the code compiles successfully but fails at runtime when the injection of the
`InventoryResource` class takes place.
You can learn about the ShrinkWrap archive configuration in this
http://arquillian.org/guides/shrinkwrap_introduction/[Arquillian guide^].

The [hotspot=ArquillianResource]`@ArquillianResource` annotation is used to retrieve the
`\http://localhost:9080/arquillian-managed/` base URL for this web service.
The annotation provides the host name, port number and web archive
information for this service, so you don't need to hardcode these values
in the test case. The `arquillian-managed` path in the URL comes
from the WAR name you specified when you created the web archive in the
[hotspot=Deployment]`@Deployment` annotated method.
It's needed when the `inventory` service communicates
with the `system` service to get the system properties.

The [hotspot=testInventoryEndpoints]`testInventoryEndpoints` method is an integration
test to test the `inventory` service endpoints. The [hotspot=RunAsClient]`@RunAsClient`
annotation added in this test case indicates that this test case is to be run
on the client side. By running the tests on the client side,
the tests are run against the managed container.
The endpoint test case first calls the
`\http://localhost:9080/{WARNAME}/inventory/systems/{hostname}` endpoint with
the `localhost` host name to add its system properties to the inventory.
The test verifies that the system property for the local and service JVM match.
Then, the test method calls the
`\http://localhost:9080/{WARNAME}/inventory/systems` endpoint.
The test checks that the inventory has one host and
that the host is `localhost`. The test also verifies that the system property
stored in the inventory for the local and service JVM match.

Contexts and Dependency Injection (CDI) is used to inject an instance of the
[hotspot=InventoryResource]`InventoryResource` class into this test class.
You can learn more about CDI in the
https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices^] guide.

The injected [hotspot=InventoryResource]`InventoryResource` instance is then tested
by the [hotspot=testInventoryResourceFunctions]`testInventoryResourceFunctions` method.
This test case calls the [hotspot=listContents]`listContents()` method to get all systems
that are stored in this inventory
and verifies that `localhost` is the only system being found.
Notice the functional test case doesn't store any system in the inventory,
the `localhost` system is from the endpoint test case that ran before this test case.
The [hotspot=InSequence1 hotspot=InSequence2]`@InSequence` Arquillian annotation guarantees the test sequence.
The sequence is important for the two tests, as the results in the first test impact the second one.

The test cases are ready to run.
You will configure the Maven build and the Liberty application server to run them.

== Configuring Arquillian with Liberty

Configure your build to use the Arquillian Liberty Managed container
and set up your Open Liberty server to run your test cases by configuring the `server.xml` file.

=== Configuring your test build

First, configure your test build with Maven. All of the Maven configuration takes
place in the [hotspot]`pom.xml` file, which is provided for you.

pom.xml
[source, xml, linenums, indent=0, role='code_column']
----
include::finish/pom.xml[]
----

Let's look into each of the required elements for this configuration.

You need the [hotspot=arquillian-bom]`arquillian-bom` Bill of Materials.
It's a Maven artifact that defines the versions of Arquillian dependencies to
make dependency management easier.

The [hotspot=arquillian-liberty-managed-junit]`arquillian-liberty-managed-junit` dependency bundle,
which includes all the core dependencies, is required to run the Arquillian tests on a
managed Liberty container that uses JUnit. You can learn more about the
https://github.com/OpenLiberty/arquillian-liberty-dependencies[Arquillian Liberty dependency bundles^].
The [hotspot=shrinkwrap-api]`shrinkwrap-api` dependency allows you to create your test
archive, which is packaged into a WAR file and deployed to the Open Liberty server.

The [hotspot=maven-failsafe-plugin]`maven-failsafe-plugin` artifact runs your Arquillian integration tests by using JUnit.

Lastly, specify the [hotspot=liberty-maven-plugin]`liberty-maven-plugin`
configuration that defines your Open Liberty runtime configuration.
The `configure-arquillian` goal configures your Arquillian container.
This goal automatically retrieves core server parameters from the `liberty-maven-plugin` configuration
and enables you to customize your Arquillian container configuration directly in your POM file if necessary.
You can learn more about the `configure-arquillian` goal in its
https://github.com/WASdev/ci.maven/blob/master/docs/configure-arquillian.md[documentation^].


=== Configuring the server.xml file

Now that you're done configuring your Maven build, set up your
Open Liberty server to run your test cases by configuring
the [hotspot]`server.xml` file.

Take a look at the [hotspot]`server.xml` file.

server.xml
[source, xml, linenums, indent=0, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

The [hotspot=localConnector]`localConnector` feature is required by the Arquillian Liberty
Managed container to connect to and communicate with the Open Liberty runtime.
The [hotspot=Servlet]`servlet` feature is required during the deployment of the
Arquillian tests in which servlets are created to perform the in-container testing.


== Running the tests

It's now time to build and run your Arquillian tests.
Navigate to the `start` directory. First, run the Maven command to package the application.
Then, run the `liberty-maven-plugin` goals to create the application server, install the features
and deploy the application to the server. The `configure-arquillian` goal configures
your Arquillian container.

[role="command"]
```
mvn clean package
mvn liberty:create liberty:install-feature liberty:deploy
mvn liberty:configure-arquillian
```

Now, you can run your Arquillian tests with the Maven `integration-test` goal:

[role="command"]
```
mvn failsafe:integration-test
```

In the test output, you can see that the application server launched, and that the web archive,
`arquillian-managed`, started as an application in the server.
You can also see that the tests are running and that the results are reported.

After the tests stop running, the test application is automatically
undeployed and the server shuts down.
You should then get a message indicating that the build and tests are successful.

[source, role="no_copy"]
----
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.inventory.InventoryArquillianIT
...
[AUDIT   ] CWWKE0001I: The server ArquillianManagedServer has been launched.
[INFO    ] CWWKE0002I: The kernel started after 2.069 seconds
[INFO    ] CWWKF0007I: Feature update started.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[INFO    ] CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host localhost  (IPv4: 127.0.0.1) port 9080.
[INFO    ] CWWKZ0018I: Starting application guide-arquillian-managed.
...
[INFO    ] SRVE0169I: Loading Web Module: guide-arquillian-managed.
[INFO    ] SRVE0250I: Web Module guide-arquillian-managed has been bound to default_host.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application guide-arquillian-managed started in 4.276 seconds.
[INFO    ] SESN0176I: A new session context will be created for application key default_host/
[INFO    ] CWWKZ0018I: Starting application arquillian-managed.
...
[AUDIT   ] CWWKF0011I: The server ArquillianManagedServer is ready to run a smarter planet.
...
[INFO    ] SRVE0169I: Loading Web Module: arquillian-managed.
[INFO    ] SRVE0250I: Web Module arquillian-managed has been bound to default_host.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/arquillian-managed/
...
[AUDIT   ] CWWKZ0001I: Application arquillian-managed started in 0.957 seconds.
...
[INFO    ] Setting the server's publish address to be /inventory/
[INFO    ] SRVE0242I: [arquillian-managed] [/arquillian-managed] [io.openliberty.guides.inventory.InventoryApplication]: Initialization successful.
[INFO    ] Setting the server's publish address to be /system/
[INFO    ] SRVE0242I: [guide-arquillian-managed] [/] [io.openliberty.guides.system.SystemApplication]: Initialization successful.
[INFO    ] SRVE0242I: [arquillian-managed] [/arquillian-managed] [ArquillianServletRunner]: Initialization successful.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/arquillian-managed/
[INFO    ] SRVE0253I: [arquillian-managed] [/arquillian-managed] [ArquillianServletRunner]: Destroy successful.
[INFO    ] SRVE0253I: [arquillian-managed] [/arquillian-managed] [io.openliberty.guides.inventory.InventoryApplication]: Destroy successful.
[AUDIT   ] CWWKZ0009I: The application arquillian-managed has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 7.923 seconds.
Server defaultServer stopped.
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.355 s - in it.io.openliberty.guides.inventory.InventoryArquillianIT
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.875 s
[INFO] Finished at: 2019-02-12T14:40:43-05:00
[INFO] ------------------------------------------------------------------------
----

== Great work! You're done!

You just built some functional and integration tests with the
Arquillian managed container and ran the tests for your microservices
on Open Liberty.

Try one of the related guides to learn more about the
technologies that you come across in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]
