// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide
:projectid: arquillian-managed
:page-duration: 20 minutes
:page-releasedate: 2018-11-30
:page-guide-category: none
:page-description: Learn how to test your microservices using the Arquillian Liberty Managed container and JUnit.
:page-tags: ['Maven']
:page-related-guides: ['cdi-intro','rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Arquillian Managed container testing
:page-seo-description: Testing your microservices with Arquillian Liberty Managed container
= Testing microservices with Arquillian Managed container

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to develop tests for your microservices using the Arquillian Liberty Managed container and run the tests in Open Liberty.

== What you'll learn
You will learn how to develop tests for your microservices using the https://github.com/OpenLiberty/liberty-arquillian/tree/master/liberty-managed[Arquillian Liberty Managed container] and JUnit with Maven in Open Liberty. You will also learn how to take advantage of features in the Liberty plugin that simplify the process of managing Arquillian dependencies and setting up your managed container.

http://arquillian.org/[Arquillian] is a testing platform to develop automated functional, integration and acceptance tests for your Java applications.

Arquillian tests looks similar to the common unit tests. The benefit of Arquillian test is that it sets up the test environment and is able to handle the application server life cycle for you, so you can focus on writing tests. Arquillian supports both JUnit and TestNG as the test runner. This guide will use the JUnit test runner. An Arquillian JUnit test has three core components, `@RunWith(Arquillian.class)`, `@Deployment` and `@Test`. Once you have these three components setup, you'll have everything you need to test your microservices. You will learn more about these components in the test class.

Arquillian allows different application servers to implement their own embedded, managed and remote containers. This guide will use the Arquillian Liberty Managed container, which is an adaptor to run Arquillian tests on or against a locally managed Liberty runtime. It's capable of managing the Liberty server operations, packaging the tests as a `WAR` to be deployed to the Liberty server and then running the tests on the server.

The application that you will work with is an `inventory` service that stores information about various systems. The `inventory` service communicates with the `system` service on a particular host to retrieve its system properties and stores them. You will learn how to configure the `inventory` service to use the Arquillian Liberty Managed container adaptor with the Maven build tool and develop functional and integration tests for the microservices to run in Open Liberty.

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

To try running the finished application with the Arquillian tests, navigate to the `finish` directory and execute the Maven build.

```
cd finish
mvn install
```

You should see the console output indicating that your build is successful and the tests have passed.

== Configuring Arquillian with Liberty

You will need to configure your build to use the Arquillian Liberty Managed container and setup the Liberty `server.xml` file before developing Arquillian test cases for your microservices and running them with Open Liberty.

Navigate to the `start` directory to begin.

=== Configuring your test build

You will start configuring your test build with Maven. All of the Maven configuration takes place in the `pom.xml` file.

Let's look into each of the required elements for this configuration. First, the `liberty-maven-app-parent` parent POM configures the Liberty Maven Plugin with the default executions necessary for setting up your managed Liberty server.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddLibertyMavenAppParent]
----

Next, the `arquillian-bom` Bill of Materials is a Maven artifact which defines the versions of Arquillian dependencies to make dependency management easier.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddArquillianBOM]
----

Next, refer to the `arquillian-liberty-managed-junit` dependency bundle and the Arquillian `shrinkwrap-api`. The dependency bundle includes all the core dependencies for running Arquillian tests on a managed Liberty container using JUnit. You can learn more about the https://github.com/OpenLiberty/arquillian-liberty-dependencies[Arquillian Liberty dependency bundles]. The Shrinkwrap API allows you to create your test archive which is packaged into a WAR file and deployed to the Open Liberty server.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddArquillianLibertyManagedJUnitAndShrinkwrapAPIDependency]
----

Finally, the `maven-failsafe-plugin` is used to run your Arquillian integration tests using JUnit, while the `liberty-maven-plugin` configuration specifies your Open Liberty runtime and uses the `configure-arquillian` goal to automatically create and configure your `arquillian.xml` file. This goal retrieves the core `wlpHome`, `serverName`, and `httpPort` parameter values automatically from the Liberty Maven Plugin configuration, and also allows you to specify additional `arquillian.xml` parameters directly in your POM in an `arquillianProperties` dictionary. You can learn more about the `configure-arquillian` goal in the https://github.com/WASdev/ci.maven/blob/master/docs/configure-arquillian.md[documentation]. Also, notice in the configuration that `skipTestServer` is set to true to skip the `test-start-server` and `test-stop-server` goals defined in the Liberty Maven Application Parent. The test server configuration is disabled because Arquillian is managing the server lifecycle when it runs the tests.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=AddMavenFailsafeAndLibertyMavenPlugins]
----

=== Configuring the server.xml

Now that you're done configuring the build tool, open the `src/main/liberty/config/server.xml` file:

[source, xml, indent=0, role="no_copy"]
----
include::finish/src/main/liberty/config/server.xml[tags=**]
----

The `localConnector` feature in the `featureManager` block is required by the Arquillian Liberty Managed container in order to connect to and communicate with the Open Liberty runtime. The `servlet` feature is required during the deployment of the Aquillian tests in which servlets are created to perform the in-container testing.

== Developing Arquillian tests

You're now ready to write your Arquillian tests for the `inventory` microservices. The code for the microservices is provided to you under the `src/main/java/io/openliberty/guides` directory. You'll develop test classes in the `src/test` directory. Recall the `inventory` service communicates with the `system` service on a particular host to retrieve its system properties and then stores it. You will develop tests that use Arquillian and JUnit to verify the `inventory` service as an endpoint and the resource functionalities.

Create the `InventoryIT` test class for the `inventory` service in the `src/test/java/it/io/openliberty/guides/inventory/InventoryIT.java` file:

[source, Java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryIT.java[tags=**;!copyright;]
----

Notice the JUnit Arquillian runner is being used to run the tests, instead of the standard JUnit runner. This is specified using the `@RunWith` annotation at the top of the class, and tells JUnit to run the tests using Arquillian.

Another important item is the `@Deployment` block.

[source, Java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryIT.java[tags=deployment]
----

The ShrinkWrap test archive's contents are defined in this block, which is going to be deployed to Open Liberty to run the in-container tests. The `testable = true` attribute enables the deployment to run in-container tests.

Notice the `arquillian-managed.war` WAR name in the web archive. This is necessary if you don't want a randomly generated web archive name. This WAR name is also needed when the `inventory` service communicates with the `system` service to get the system properties.

All of the packages in this service must be added to the web archive, otherwise, the code compiles successfully but fails at runtime when the injection of the testing resource class takes place. You can learn about the ShrinkWrap archive configuration in the  http://arquillian.org/guides/shrinkwrap_introduction/[Arquillian guide].

The `@ArquillianResource` annotation is used to retrieve the base URL for this web service.
This annotation provides the hostname, port number and web archive information for this service,
so you do not need to hard code these values in the test case.

The `testGetPropertiesFromEndpoint` test case is an integration test to test the `inventory` service endpoints. The `@RunAsClient` annotation added in this test case indicates that this test case is to be run on the client side, which means the tests are run against the managed container. The endpoint test case first calls the `http://localhost:9080/{WARNAME}/inventory/systems/{hostname}` endpoint with the `localhost` hostname, to add its system properties to the inventory. The test verifies that the system property for the local and service JVM match. Then, the test method calls the `http://localhost:9080/{WARNAME}/inventory/systems` endpoint. The test checks that the inventory should have one host registered and that should be `localhost`. The test also verifies that the system property stored in the inventory for the local and service JVM match.

Next, refer to the `testInventoryResourceFunctions` test case, which is a functional test case for the `InventoryResource` class.

CDI is used to inject an instance of the `InventoryResource` class into this test class. It is then tested by the `testGetPropertiesFromFunction` method, which validates that the system property for the local and service JVM match. This test case calls the `listContents()` method to get all systems that are stored in this inventory and verifies that one system is found and it is `localhost`.Notice the functional test case does not store any system in the inventory, the `localhost` system is from the endpoint test case that ran prior to this test case. The `@InSequence` Arquillian annotation guarantees the test sequence. The sequences are important for the two test methods, as the results in the first test impacts the second one.

== Running the tests

It's now time to build and run your Arquillian test. Run the Maven build command in the `start` directory.

```
mvn install
```

In the test output, you see the application server was launched, and that the ShrinkWrap web archive, `arquillian-managed` is started as an application in the server. Then, the tests are being run and the results are reported.

Following the execution of the tests, the test application is automatically undeployed and the server is shut down. You should then get a message indicating that the build and tests are successful.

== Great work! You're done!

You have just completed building some functional and integration tests with the Arquillian Liberty Managed container to run the tests for your microservices in Open Liberty.

You can continue to try one of the related guides to learn more about the technologies that you have come across in this guide.

include::{common-includes}/finish.adoc[]
